return {
	armhavp = {
		buildangle = 1024,
		builder = true,
		buildpic = "ARMVP.DDS",
		buildtime = 14400,
		canmove = true,
		collisionvolumescales = "120 34 92",
		collisionvolumetype = "Box",
		corpse = "DEAD",
		energycost = 3600,
		energystorage = 200,
		explodeas = "largeBuildingexplosiongeneric",
		footprintx = 6,
		footprintz = 6,
		health = 6000,
		idleautoheal = 5,
		idletime = 1800,
		levelground = false,
		maxacc = 0,
		maxdec = 0,
		maxslope = 15,
		maxwaterdepth = 0,
		metalcost = 1480,
		metalstorage = 200,
		objectname = "Units/ARMAMSUB.s3o",
		script = "Units/ARMAMSUB.cob",
		seismicsignature = 0,
		selfdestructas = "largeBuildingExplosionGenericSelfd",
		sightdistance = 273,
		terraformspeed = 500,
		workertime = 400,
		yardmap = "oooooo oooooo oooooo oeeeeo oeeeeo oeeeeo",
		buildoptions = {
			[1] = "armconsul",
			[2] = "armbeaver",
			[3] = "armmlv",
			[4] = "armlatnk",
			[5] = "armmart",
			[6] = "armpincer",
			[7] = "armgremlin",
			[8] = "armcroc",
		},
		customparams = {
			buildinggrounddecaldecayspeed = 30,
			buildinggrounddecalsizex = 11,
			buildinggrounddecalsizey = 11,
			buildinggrounddecaltype = "decals/armamsub_aoplane.dds",
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmBuildings/SeaFactories",
			unitgroup = "builder",
			usebuildinggrounddecal = true,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "-5 0 0",
				collisionvolumescales = "110 34 92",
				collisionvolumetype = "Box",
				damage = 1668,
				featuredead = "HEAP",
				footprintx = 6,
				footprintz = 6,
				height = 40,
				metal = 966,
				object = "Units/armamsub_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 834,
				footprintx = 6,
				footprintz = 6,
				height = 4,
				metal = 386,
				object = "Units/arm6X6A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			unitcomplete = "unitready",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			select = {
				[1] = "vehplantselect",
			},
		},
	},
}
